### DISCUSSION TITLE
.NET 8.0 support for API using Sqlite3 database in App_Data folder

### DISCUSSION THREAD

**Discussion by ganeshan** [ServiceStack/Discuss#101] [Q&A]
Hi, I am using Sqlite3 database in App_Data folder. The project is a Blazor project based on .NET 8.0
`x new blazor MyApp`
I can use dotnet publish to create a docker image. However, when I run the app, I am getting an error that complains about not able to open database from /app/App_Data. Do I need to make changes to Dockerfile or add additional code? Is there a way to run dotnet run --AppTasks=migrate to create and populate the sqlite database?
As per one of the videos posted by ServiceStack, .NET 8.0 has build in support for Docker using `dotnet publish`, however, the blazor template uses Dockerfile, can you please explain why it is so? Thanks in advance

**Comment by Layoric** [comment]
The `App_Data` folder when running under docker is setup with GitHub Actions as somewhere your application can write to. The configured GitHub Actions also runs the `dotnet run --AppTasks=migrate` within the container. The GitHub actions do this via `docker compose` using the command [`docker compose up app-migration --exit-code-from app-migration`](https://github.com/NetCoreTemplates/blazor/blob/main/.github/workflows/release.yml#L137).

This creates the database, and runs any outstanding migrations for your application. Locally, when you run `dotnet publish`, it will create the application container and push it to your local Docker repository, usually Docker Desktop. So before you run your newly created container, you want to run the `AppTasks=migrate` first, also ensuring that both are using the same volume mounting/pointing to the same file path on your file system. 

One way you can do this is to use `docker compose`, you could create your own copy of the [`docker-compose.yml`](https://github.com/NetCoreTemplates/blazor/blob/main/.deploy/docker-compose.yml) file that comes with the template, but pointing locally since that version always points to GitHub Container Registry. If you create [a `.env` file](https://docs.docker.com/compose/environment-variables/set-environment-variables/) to populate the all the options you have locally to more easily rerun.

If you create a `docker-compose.yml` file like below to work locally:

```
version: "3.9"
services:
    app:
        image: {IMAGE_NAME}
        restart: always                               
        ports:                                         
            - "8080"                                     
        container_name: ${APP_NAME}_app                
        environment:
            LC_ALL: "en_US.UTF-8"
            LANG: "en_US.UTF-8"
        volumes:
            - ./App_Data:/app/App_Data  

    app-migration:
        image: ghcr.io/${IMAGE_REPO}:${RELEASE_VERSION} 
        restart: "no"                                  
        container_name: ${APP_NAME}_app_migration       
        profiles:                                      
            - migration                                
        command: --AppTasks=migrate                     
        volumes:
            - ./App_Data:/app/App_Data                                        
```

Along with a `.env` file like:

```
IMAGE_NAME=<your app name, default is `myapp`>
RELEASE_VERSION=latest
APP_NAME=<your app name, default is `myapp`>
```

Then with the command line you can run:

```
docker compose up app-migration
```

And then run your app:

```
docker compose up app -d
```

Let us know how you go.
